[package]
name = "advent_of_code_2023"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "01_1"
path = "src/01_1.rs"

[[bin]]
name = "01_2"
path = "src/01_2.rs"

[[bin]]
name = "02_1"
path = "src/02_1.rs"

[dependencies]
image = "0.24.7"
rand = "0.8.5"
rusttype = "0.9.3"
speedy2d = "2.0.0"
